server {
    listen 80;
    server_name _;

    root /var/www/public;
    index index.php index.html;

    charset utf-8;

    # Assets do Vite
    location /build/ {
        try_files $uri =404;
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Front controller (Laravel)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM
    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_pass app_web_app:9000;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
