CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO users (name, email, password)
VALUES ('Admin User', 'admin@example.test', '$2y$10$LmhcV5BtiUTtrKLXSBTl..BP/ZceuEL/rYA9cVgUrM9mTCtgadonO')
ON DUPLICATE KEY UPDATE email = VALUES(email);
